### Error Handling

#### Default error values

Integrity matters. Nothing trumps integrity. Therefore, part of integrity is error handling. It is a big part of what we do everyday. It has to be a part of the main code. First, let's look at the language mechanic first on how the default error type is implemented.

```go
package​ main
import​ ​"fmt"
```

http://golang.org/pkg/builtin/#error

This is pre-included in the language so it looks like an unexported type. It has one active behavior, which is Error returned a string. Error handling is decoupled because we are always working with error interface when we are testing our code.

Errors in Go are really just values. We are going to valuate these through the decoupling of the interface. Decoupling error handling means that cascading changes will bubble up through the user application, causes cascading wide effect through the code base. It's important that we leverage the interface here as much as we can.

```go
type​ error ​interface​ {
    Error() ​string
}
```

http://golang.org/src/pkg/errors/errors.go

This is the default concrete type that comes from the error package. It is an unexported type that has an unexported field. This gives us enough context to make us form a decision.

We have responsibility around error handling to give the caller enough context to make them form a decision so they know how to handle this situation.

```go
type​ errorString ​struct​ {
    s ​string
}
```

http://golang.org/src/pkg/errors/errors.go

This is using a pointer receiver and returning a string. If the caller must call this method and parse a string to see what is going on then we fail.

This method is only for logging information about the error.

```go
func​ (e *errorString) ​Error​() ​string​ {
    return​ e.s
}
```

http://golang.org/src/pkg/errors/errors.go

New returns an error interface that formats as the given text. When we call New, what we are doing is creating errorString value, putting some sort of string in there.. Since we are returning the address of a concrete type, the user will get an error interface value where the first word is a \*errorString and the second word points to the original value. We are going to stay decoupled during the error handling.

```go
func​ ​New​(text ​string​) ​error​ {
    return​ &errorString{text}
}
```

This is a very traditional way of error handling in Go. We are calling webCall and returning the error interface and storing that in a variable.

nil is a special value in Go. What "error != nil" actually means is that we are asking if there is a concrete type value that is stored in error type interface. Because if error is not nil, there is a concrete value stored inside. If it is the case, we've got an error.

Now do we handle the error, do we return the error up the call stack for someone else to handle? We will talk about this later.

```go
func​ ​main​() {
    if​ err := webCall(); err != ​nil​ {
        fmt.Println(err)
        return
    }
    fmt.Println(​"Life is good"​)
}
```

webCall performs a web operation.

```go
func​ ​webCall​() ​error​ {
    return​ New(​"Bad Request"​)
}
```

#### Error variables

Let’s use error variables to determine the exact error being returned.

```go
package​ main
import​ (
    "errors"
    "fmt"
)
```

We want these to be on the top of the source code file. Naming convention: starting with Err. They have to be exported because our users need to access them.

These are all error interfaces that we have discussed in the last file, with variables tied to them. The contexts for these errors are the variables themselves. This allows us to continue using the default error type, that unexported type with unexported field to maintain a level of decoupling through error handling.

ErrBadRequest is returned when there are problems with the request. ErrPageMoved is returned when a 301/302 is returned.

```go
var​ (
    ErrBadRequest = errors.New(​"Bad Request"​)
    ErrPageMoved = errors.New(​"Page Moved"​)
)
```

```go
func​ ​main​() {
    if​ err := webCall(​true​); err != ​nil​ {
        switch​ err {
        case​ ErrBadRequest:
            fmt.Println(​"Bad Request Occurred"​)
            return
        case​ ErrPageMoved:
            fmt.Println(​"The Page moved"​)
            return
        default​:
            fmt.Println(err)
            return
        }
    }
    fmt.Println(​"Life is good"​)
}
```

webCall performs a web operation.

```go
func​ ​webCall​(b ​bool​) ​error​ {
    if​ b {
        return​ ErrBadRequest
    }
    return​ ErrPageMoved
}
```

```
Bad Request Occurred
```

#### Type as context

It is not always possible to be able to say the interface value itself will be enough context. Sometimes, it requires more context. For example, a networking problem can be really complicated. Error variables wouldn't work there. Only when the error variables wouldn't work, we should go ahead and start working with a custom concrete type for the error.

Below are two custom error types from the JSON package in the standard library and how we can use those. This is type as context.

http://golang.org/src/pkg/encoding/json/decode.go

```go
package main
import​ (
    "fmt"
    "reflect"
)
```

An UnmarshalTypeError describes a JSON value that was not appropriate for
a value of a specific Go type. Naming convention: The word "Error" ends at the name of the type.

```go
type​ UnmarshalTypeError ​struct​ {
    Value ​string​ ​// description of JSON value
    Type reflect.Type ​// type of Go value it could not be assigned to
}
```

UnmarshalTypeError implements the error interface. We are using pointer semantics. In the implementation, we are validating all the fields being used in the error message. If not, we have a problem. Because why would you add a field to the custom error type and not displaying it on your log when this method would call. We only do this when we really need it.

```go
func​ (e *UnmarshalTypeError) ​Error​() ​string​ {
    return​ ​"json: cannot unmarshal "​ + e.Value + ​" into Go value of type "​ + e.Type.String()
}
```

An InvalidUnmarshalError describes an invalid argument passed to Unmarshal. The argument to Unmarshal must be a non-nil pointer. This concrete type is used when we don't pass the address of a value into the Unmarshal function.

```go
type​ InvalidUnmarshalError ​struct​ {
    Type reflect.Type
}
```

InvalidUnmarshalError implements the error interface.

```go
func​ (e *InvalidUnmarshalError) ​Error​() ​string​ {
    if​ e.Type == ​nil​ {
        return​ ​"json: Unmarshal(nil)"
    }
    if​ e.Type.Kind() != reflect.Ptr {
        return​ ​"json: Unmarshal(non-pointer "​ + e.Type.String() + ")"
    }
    return​ ​"json: Unmarshal(nil "​ + e.Type.String() + ​")"
}
```

user is a type for use in the Unmarshal call.

```go
type​ user ​struct​ {
    Name ​int
}
```

```go
func​ ​main​() {
    var​ u user
    err := Unmarshal([]​byte​(​`{"name":"bill"}`​), u) ​// Run with a value and pointer.
    if​ err != ​nil​ {
        This is a special ​type​ assertion that only works on the ​switch​.
​        switch​ e := err.(​type​) {
        case​ *UnmarshalTypeError:
            fmt.Printf(​"UnmarshalTypeError: Value[%s] Type[%v]\n"​, e.Value, e.Type)
        case​ *InvalidUnmarshalError:
            fmt.Printf(​"InvalidUnmarshalError: Type[%v]\n"​, e.Type)
        default​:
            fmt.Println(err)
        }
        return
    }
    fmt.Println(​"Name:"​, u.Name)
}
```

Unmarshal simulates an unmarshal call that always fails. Notice the parameters here: The first one is a slice of byte and the second one is an empty interface. The empty interface basically says nothing, which means any value can be passed into this function. We are going to reflect on the concrete type that is stored inside this interface and we are going to validate that it is a pointer or not nil. We then return different error types depending on these.

```go
func​ ​Unmarshal​(data []​byte​, v ​interface​{}) ​error​ {
    rv := reflect.ValueOf(v)
    if​ rv.Kind() != reflect.Ptr || rv.IsNil() {
        return​ &InvalidUnmarshalError{reflect.TypeOf(v)}
    }
    return​ &UnmarshalTypeError{​"string"​, reflect.TypeOf(v)}
}
```

There is one flaw when using type as context here. In this case, we are now going back to the concrete. We walk away from the decoupling because our code is now bound to these concrete types. If the developer who wrote the json package makes any changes to these concrete types, that's gonna create a cascading effect all the way through our code. We are no longer protected by the decoupling of the error interface.

This sometimes has to happen. Can we do something different not to lose the decoupling. This is where the idea of behavior as context comes in.

#### 컨텍스트로서의 기능(Behavior as context)

컨텍스트로서의 기능은 사용자 정의 오류를 마치 컨텍스트처럼 다룰 수 있게 해준다. 하지만 타입 단언이 구체적인 형태로 돌아가는 건 막는다. 이로써 디커플링(decoupling)의 레벨에서 코드를 유지보수할 수 있게 되었다.

```go
package​ main
import​ (
    "bufio"
    "fmt"
    "io"
    "log"
    "net"
)
```

`client`는 하나의 연결성을 가진다.

```go
type​ client ​struct​ {
    name ​string
    reader *bufio.Reader
}
```

`TypeAsContext`는 `net` 패키지가 반환하는 여러 사용자 정의 오류들을 확인하는 방법을 보여준다.

```go
func​ (c *client) ​TypeAsContext​() {
    for​ {
```

네트워크에서 받아온 데이터를 `reader`를 통해 분리한다.

```go
        line, err := c.reader.ReadString(​'\n'​)
        if​ err != ​nil​ {
```

이 예제는 이전 예제와 마찬가지로 타입을 컨텍스트처럼 쓴다. 여기서는 `Temporary`라는 메서드가 중요하다. 이 메서드가 정상적으로 작동한다면 계속 작업을 수행하고 그렇지 않다면 일단 멈춘 후에 다시 시작한다. 아래 모든 케이스는 오직 `Temporary`만을 위한 것이다. 이게 왜 중요한가? 만약 타입 단언을 한다거나 구현된 타입의 잠재적인 기능만 요구한다면, 이것을 컨텍스트로서의 타입을 기능으로서의 타입으로 바꿀 수 있다. 그렇기에 아래의 `temporary`라는 사용자 정의 인터페이스를 만들 수 있다.

```go
            switch​ e := err.(​type​) {
            case​ *net.OpError:
                if​ !e.Temporary() {
                    log.Println(​"Temporary: Client leaving chat"​)
                    return
                }
            case​ *net.AddrError:
                if​ !e.Temporary() {
                    log.Println(​"Temporary: Client leaving chat"​)
                    return
                }
            case​ *net.DNSConfigError:
                if​ !e.Temporary() {
                    log.Println(​"Temporary: Client leaving return chat")
                    return
                }
            default​:
                if​ err == io.EOF {
                    log.Println(​"EOF: Client leaving chat"​)
                    return
                }
            log.Println(​"read-routine"​, err)
            }
        }
    fmt.Println(line)
    }
}
```

`temporary`는 net 패키지에서 `Temporary`라는 메서드가 반환되는 지 확인한다. 왜냐하면 그 중 `Temporary`라는 메서드를 가진 구조체만 있으면 되기때문이다. 그러면 여전히 디커플링 단계에 있으며 계속 인터페이스 레벨에서 작업할 수 있다.

```go
type​ temporary ​interface​ {
    Temporary() ​bool
}
```

`BehaviorAsContext`는 `net` 패키지가 반환할 지도 모르는 있는 인터페이스를 어떻게 확인하는 지 보여준다.

```go
func​ (c *client) ​BehaviorAsContext​() {
    for​ {
        line, err := c.reader.ReadString(​'\n'​)
        if​ err != ​nil​ {
            switch​ e := err.(​type​) {
```

타입 단언을 통해 세가지 경우를 한가지 경우로 줄일 수 있다:
이 구현 타입은 해당 인터페이스를 구현하고 있는 `error` 인터페이스를 가지고 있으며 해당 인터페이스를 정의하고 이용할 수 있다.

```go
            case​ temporary:
                if​ !e.Temporary() {
                    log.Println(​"Temporary: Client leaving return chat")
                    return
                }
            default​:
                if​ err == io.EOF {
                    log.Println(​"EOF: Client leaving chat"​)
                    return
                }
                log.Println(​"read-routine"​, err)
            }
        }
        fmt.Println(line)
    }
}
```

**Lesson:**

Go의 암시적 형변환 덕분에, 원하는 메서드나 기능을 가진 인터페이스를 구현함으로 디커플링 단계에서 유지보수할 수 있고 타입 단언을 이용하는 `switch` 문법에서 구현 타입 대신에 사용할 수 있다.

#### 버그 사냥(Finding the bug)

```go
package​ main
import​ ​"log"
```

`customError`는 빈 구조체이다.

```go
type​ customError ​struct​{}
```

`Error`는 `error` 인터페이스를 구현한다.

```go
func​ (c *customError) ​Error​() ​string​ {
    return​ ​"Find the bug."
}
```

`fail` 함수는 둘 다 `nil` 값을 반환한다.

```go
func​ ​fail​() ([]​byte​, *customError) {
    return​ ​nil​, ​nil
}
```

```go
func​ ​main​() {
    var​ err error
```

`fail`을 호출하면 `nil` 값을 반환할 것이다. 하지만 `error` 인터페이스로써 반환하고 싶지만 `customError` 타입의 `nil` 값을 반환할 뿐이다. `customError` 타입은 이 소스 코드 안에서 만들어진 타입에 불과하다. 그렇기에 사용자 정의 타입을 직접 반환해서는 안되고 `func fail() ([]byte, error)` 처럼 인터페이스를 반환해야한다.

```go
    if​ _, err = fail(); err != ​nil​ {
        log.Fatal(​"Why did this fail?"​)
    }
    log.Println(​"No Error"​)
}
```

#### 에러 포장(Wrapping Errors)

오류 처리는 코드의 일부이며, 로깅으로 까지 이어진다. 로깅의 주목적은 디버그를 위한 것이다. 로그를 보고 대응이 가능한 것이라면 로그로 남긴다. 어떻게 실행되고 있는지 상황을 알려주는 것을 로그로 남긴다. 그 외의 것들은 노이즈나 다름 없으며, 대시보드의 지표로나 사용하면 된다. 예를 들자면, 소켓의 연결과 끊어짐을 로그로 남길 수는 있지만 딱히 대응을 해야 하거나 챙겨서 볼 필요는 없는 것이다.

여기 Dave Cheney가 작성한 `errors`라는 패키지가 있다. 이 패키지는 오류를 간단하게 처리할 수 있게 도와주고 동시에 로그를 기록해준다. 아래 코드는 이 패키지가 코드를 어떻게 단순하게 만들어 주는 지 보여준다. 로깅의 양을 줄임으로, 힙(주로 Garbage Collection)에 대한 부담을 줄일 수 있다.

```go
import (
    "fmt"

    "github.com/pkg/errors"
)
```

`AppError`는 사용자 정의 에러 타입이다.

```go
type​ AppError ​struct​ {
    State ​int
}
```

`AppError`는 `error` 인터페이스를 구현한다.

```go
func​ (c *AppError) ​Error​() ​string​ {
    return​ fmt.Sprintf(​"App Error, State: %d"​, c.State)
}
```

```go
func​ ​main​() {
```

함수를 호출하고 오류를 검증한다. `firstCall`은 `secondCall`를 호출하고 `secondCall`이 `thirdCall`을 호출하면 결과로 `AppError`가 반환된다. 호출 스택을 내려가다가 오류가 발생하는 `thirdCall`에 도달한다. 이 곳이 오류가 발생한 근원지이다. 이 오류는 `error` 인터페이스에 담겨서 호출 스택을 거슬러 올라간다.

`secondCall`로 돌아오면 `error` 인터페이스가 반환되며 그 내부엔 구현된 타입이 값으로 존재한다. `secondCall`은 오류를 처리할 수 없으면 올려보내거나 직접 처리할 지 결정해야한다. `secondCall`에서 오류를 처리하기로 결정한다면 로그로 남겨야할 책임이 주어지고 그렇지 않다면 이 책임은 호출 스택을 따라 거슬러 올라가게 된다. 하지만 호출 스택을 밀어 올린다더라도 컨텍스트를 잃지는 않는다. `error` 패키지가 들어올 시점이다. 이러한 오류를 새로운 문맥으로 래핑하거나 추가하여 새로운 인터페이스 값을 만든다. 이것은 코드 상의 호출 스택을 보여준다.

`firstCall`은 오류를 처리하지는 않지만 래핑해서 위로 올려준다. `main`에서 해당 오류를 처리하고 로그를 남기게 된다.

이 오류를 적절히 처리하기 위해서는 처음 발생한 오류, 래핑되지 않은 원시 오류에 대해 알 필요가 있다. `Cause` 메서드는 오류를 이러한 래핑으로부터 끌어내어 사용 가능한 모든 언어적 기술을 이용할 수 있게 해준다.

`State`에 접근하는 것뿐만 아니라, 구현 타입으로 단언했더라도 %+v를 이용하여 전체 스택 트레이스(stack trace)를 추적할 수 있다.

컨텍스트로서의 타입을 이용하여 사용자 정의 오류로 밝혀낸다.

```go
    if​ err := firstCall(​10​); err != ​nil​ {
        switch​ v := errors.Cause(err).(​type​) {
        case​ *AppError:
            fmt.Println(​"Custom App Error:"​, v.State)
```

오류의 스택 트레이스(stack trace)를 보여준다.

```go
            fmt.Println(​"\nStack Trace\n********************************"​)
            fmt.Printf(​"%+v\n"​, err)
            fmt.Println(​"\nNo Trace\n********************************"​)
            fmt.Printf(​"%v\n"​, err)
        }
    }
}
```

`firstCall`은 `secondCall`을 호출하고 오류를 래핑하여 반환한다.

```go
func​ ​firstCall​(i ​int​) ​error​ {
    if​ err := secondCall(i); err != ​nil​ {
        return​ errors.Wrapf(err, ​"firstCall->secondCall(%d)"​, i)
    }
    return​ ​nil
}
```

`secondCall`은 `thirdCall`을 호출하고 오류를 래핑하여 반환한다.

```go
func​ ​secondCall​(i ​int​) ​error​ {
    if​ err := thirdCall(); err != ​nil​ {
        return​ errors.Wrap(err, ​"secondCall->thirdCall()"​)
    }
    return​ ​nil
}
```

`thirdCall` 함수는 검사될 오류를 만든다.

```go
func​ ​thirdCall​() ​error​ {
    return​ &AppError{​99​}
}
```

```
Custom App Error: 99
Stack Trace
********************************
App Error, State: 99
secondCall->thirdCall()
main.secondCall
    /tmp/sandbox880380539/prog.go:74
main.firstCall
    /tmp/sandbox880380539/prog.go:65
main.main
    /tmp/sandbox880380539/prog.go:43
runtime.main
    /usr/local/go-faketime/src/runtime/proc.go:203
runtime.goexit
    /usr/local/go-faketime/src/runtime/asm_amd64.s:1373
firstCall->secondCall(10)
main.firstCall
    /tmp/sandbox880380539/prog.go:66
main.main
    /tmp/sandbox880380539/prog.go:43
runtime.main
    /usr/local/go-faketime/src/runtime/proc.go:203
runtime.goexit
    /usr/local/go-faketime/src/runtime/asm_amd64.s:1373

No Trace
********************************
firstCall->secondCall(10): secondCall->thirdCall(): App Error, State: 99
```
